### ISSUE TITLE
async support

### ISSUE THREAD

**Issue by srijs** [awslabs/aws-lambda-rust-runtime#14]
Given that the runtime is built on top of tokio, I think it would be useful to be able to provide async handler functions.

Happy to contribute this if there is interest from your side!

EDIT: Support for `tower` via the [`tower-service`](https://crates.io/crates/tower-service) crate could also be interesting.

**Comment by davidbarsky** [comment]
> Given that the runtime is built on top of tokio, I think it would be useful to be able to provide async handler functions.
> EDIT: Support for tower via the tower-service crate could also be interesting.

That's the approach I was considering; I'd love to rewrite a big portion of this library using Tower. The concern I had—and I spoke to Carl Lerche about this earlier today—is that I'd like to have _more_ of Tower (retry, balance, etc) on Crates.io before we commit to using Tower. The other concern I had is that Hyper's service is not the same as Tower's service, and I'm not sure of how to best resolve until everything is moved over in one big shift.

> Happy to contribute this if there is interest from your side!

We'd be very happy to accept contributions, especially if this isn't too much effort on your end!

**Comment by sapessi** [comment]
To add a little context here @srijs, we did not prioritize async handlers because the Lambda service itself enforces one event per environment at a time.

**Comment by softprops** [comment]
I'd to see this continue slim as it can be. Is tower slimmer than hyper in some way. I'd like to get more familiar what is gained by the extra dependencies. My understanding is the provided is a long polling based runtime, you only handle one task at a time and that lambda's scaling model was to spin up more instances when that's not sufficient. If that's correct I'm not sure what would be gained from the async interface.

**Comment by davidbarsky** [comment]
> Is tower slimmer than hyper in some way.

Not necessarily, but we've run into bugs (prior to release) that could have been prevented if we used off-the-shelf tools provided by Tower. Additionally, Hyper _currently_ has a [Service trait](https://docs.rs/hyper/0.12.17/hyper/service/trait.Service.html) that's based off Tower's Service trait, but isn't mutually interchangeable with Tower's service trait. Defining the runtime in terms of Tower allows us to use Tower's crates that provide retries, mocks, and timeout features. Additionally, it'll make it easier for customers to define their handler in terms of a Tower service, allowing them to leverage a vast and robust middleware ecosystem that provides instrumentation tooling like the upcoming [tokio-trace](https://github.com/hawkw/tokio-trace-prototype). Given that using serverless technologies like AWS Lambda make the use of instrumentation tooling even more critical, we'd like to provide hooks to customers that make it easy for them to do the right thing.

>  My understanding is the provided is a long polling based runtime, you only handle one task at a time.

Yes, that is correct—Lambda currently works like that.

>  If that's correct I'm not sure what would be gained from the async interface.

Nothing directly, performance-wise, but we'd like to build on Rust's async tooling so that we're not re-implementing a bunch of stuff and allow our customers to do the same.

**Comment by srijs** [comment]
Additionally, in my mind there's two things that I'd like to get out of an `async` API:

- Ergonomics: Most lambda code I write ends up doing outbound network requests (e.g. to other AWS APIs), and this code is be async. Being able to slot in a function returning a future directly into the `lambda!` macro, instead of having to write wrapper functions, would be super convenient.

- Cancellation: The golang runtime has this useful feature where the `context.Context` is cancelled once the lambda exceeds its deadline. Given that futures in Rust have cancellation built-in, it would be super cool if this just worked out of the box.

**Comment by davidbarsky** [comment]
@srijs Those are all good points! Thanks for adding them.

> I haven't had time to look into it this weekend, but experimenting with an implementation for this is high on my to-do list!

No worries! Shoot me an email (in commits on this repo) or a Twitter DM if you've got any questions. I'm thinking we should create a Discord room (or piggy-back on a Slack room elsewhere...) to discuss this kinda stuff.

Out of curiosity, do know if Rusoto intends to move to Tower in the near future? (I hate asking y'all to do work that Amazon should own, but internal politics and prioritization is _a thing_).

**Comment by nappa85** [comment]
Hello there,
I lost a few hours to create a wanna-be drop-in improvement of the runtime to enable async support: https://github.com/nappa85/aws-lambda-rust-runtime

On my tests it works fine, it just needs a new Tokio dep on the implemtation.
Any comment is appreciated.

**Comment by RodrigoLeiteF** [comment]
@nappa85 Would you mind adding a simple example to your fork? I'd like to test it (using Futures), but can't seem to figure out what the Error trait should be :p

**Comment by nappa85** [comment]
> @nappa85 Would you mind adding a simple example to your fork? I'd like to test it (using Futures), but can't seem to figure out what the Error trait should be :p

Nothing changed on the error typing, anyway I've added an example explicitly using futures: lambda-runtime/examples/custom_error_failure_future.rs
Let me know if it has solved your doubts.

**Comment by naftulikay** [comment]
Since [`lambda_runtime_core::start`](https://docs.rs/lambda_runtime_core/0.1.2/lambda_runtime_core/fn.start.html) takes an `Option<TokioRuntime>`, I assume that it's possible to do [`Runtime::block_on`](https://docs.rs/tokio/0.1.19/tokio/runtime/struct.Runtime.html#method.block_on) to spawn a futures tree and wait for all of them to complete.

However, `Runtime::block_on` blocks the calling thread, right? If this is the case, then the Lambda will only be able to execute _n_ requests in parallel, where _n_ is the number of threads spun up by Tokio, which is going to be one per logical CPU by default.

Is it basically not possible right now to do task-based concurrency in the Rust Lambda runtime crate?

**Comment by sbditto85** [comment]
To add my 0.02. I would like to have async/runtime exposed in some way so that i could reuse the runtime with rusoto instead of have 2 runtimes spun up (rusoto's sync on their future uses a lazy_static runtime) as I don't want to have to pay for 2 tokio runtimes of spin up time and resources when it really in unnecessary

**Comment by skorobkov** [comment]
> To add my 0.02. I would like to have async/runtime exposed in some way so that i could reuse the runtime with rusoto instead of have 2 runtimes spun up (rusoto's sync on their future uses a lazy_static runtime) as I don't want to have to pay for 2 tokio runtimes of spin up time and resources when it really in unnecessary

You can try this branch https://github.com/awslabs/aws-lambda-rust-runtime/tree/async-await

**Comment by algermissen** [comment]
Hi, 
I am also very interested in seamless interop between lambda runtime and tokio-based async task scheduling. Where can I find the latest updates on this topic?

**Comment by naftulikay** [comment]
I cannot promise anything at this stage, but I'm privately working on what will be an open source Lambda runtime with async support. The goal right now is to use Actix as a client in an endless loop, polling the next endpoint and returning results as they are ready. Actix was an arbitrary choice and my hope is that this can be generalized to most different web frameworks. I specifically want a runtime where I can receive events as a Lambda enum, and dispatch API gateway events right into an Actix web service so that I can take advantage of Actix middleware etc.

If you want to build your own runtime, I documented most of what's necessary [here](https://gist.github.com/naftulikay/f433e9ddc2727f05288b8606fa1ccfb0).

**Comment by softprops** [comment]
With async support on master, I think we can close this issue

**Comment by bahildebrand** [comment]
Async is available on master. Closing this issue.
