### ISSUE TITLE
Handler Error type on Master

### ISSUE THREAD

**Issue by aklitzke** [awslabs/aws-lambda-rust-runtime#229]
On current master, the handler requires an `anyhow::Error` as the error type for the handler, as opposed to `Box<dyn std::error::Error + Send + Sync + 'static>` in previous versions. However, this new type isn't re-exported from lib, requiring consumers of this crate to also import `anyhow`. Is this going to stick around? Maybe it would make sense to reexport your error type?

**Comment by davidbarsky** [comment]
No, it should be `Box<dyn std::error::Error + Send + Sync + 'static>`. This is a bug, sorry about that. I was lazy in some refactoring and forgot to remove `anyhow::Error`.

**Comment by softprops** [comment]
I got this. Covered in https://github.com/awslabs/aws-lambda-rust-runtime/pull/231

**Comment by davidbarsky** [comment]
Sorry about that, @aklitzke! This should be resolved now.

**Comment by aklitzke** [comment]
Awesome, thanks!

Not sure what your strategy is around testing, but should there maybe be some testing around this? Surprised you'd be able to make a breaking change to the api like that and not have some tests/examples fail to compile or something

**Comment by softprops** [comment]
Few thoughts there. 

1) the state of the current code is always going to be in sync with the tests by virtual of ci. If apis change the tests likely will as well

2) the state of the master branch reflects the current state of development, not a release. Depending on the current state of development comes with the higher risk of changes commit to commit up until a release

3) the next release will not be a patch release! Expect some changes from what's hosts on crates.io. all good and useful changes (we hope)

4) I think it's fair to have some tests that capture a contract for the error type but in the case of current master we've opted not to expose a type alias and instead rely on users to Box up a dyn std Error. Internally we use a type alias. Perhaps on thing that could be improved is type tests to capture it's properties so that when it's type does change we know we're sticking with those well known properies
