### ISSUE TITLE
Outdated LambdaRequest enum?

### ISSUE THREAD

**Issue by tocisz** [awslabs/aws-lambda-rust-runtime#256]
When trying to run [this example project](https://github.com/softprops/serverless-aws-rust-http) I have `Error("data did not match any variant of untagged enum LambdaRequest", line: 0, column: 0)`.

Request was generated by API Gateway - Method Test functionality. I was able to get it as `serde_json::Value` and print to console (with modified [this example](https://github.com/softprops/serverless-aws-rust)):

```
{
    "body": null,
    "headers": null,
    "httpMethod": "GET",
    "isBase64Encoded": false,
    "multiValueHeaders": null,
    "multiValueQueryStringParameters": null,
    "path": "/webhook",
    "pathParameters": null,
    "queryStringParameters": null,
    "requestContext": {
        "accountId": "988149861097",
        "apiId": "isc1vm0s24",
        "domainName": "testPrefix.testDomainName",
        "domainPrefix": "testPrefix",
        "extendedRequestId": "SC3wMFXDjoEFuWg=",
        "httpMethod": "GET",
        "identity": {
            "accessKey": "....",
            "accountId": "988149861097",
            "apiKey": "test-invoke-api-key",
            "apiKeyId": "test-invoke-api-key-id",
            "caller": "988149861097",
            "cognitoAuthenticationProvider": null,
            "cognitoAuthenticationType": null,
            "cognitoIdentityId": null,
            "cognitoIdentityPoolId": null,
            "principalOrgId": null,
            "sourceIp": "test-invoke-source-ip",
            "user": "988149861097",
            "userAgent": "aws-internal/3 aws-sdk-java/1.11.829 Linux/4.9.217-0.1.ac.205.84.332.metal1.x86_64 OpenJDK_64-Bit_Server_VM/25.262-b10 java/1.8.0_262 vendor/Oracle_Corporation",
            "userArn": "arn:aws:iam::988149861097:root"
        },
        "path": "/webhook",
        "protocol": "HTTP/1.1",
        "requestId": "32e4649f-b5de-40c7-b88f-c103e0ccb855",
        "requestTime": "29/Aug/2020:18:35:45 +0000",
        "requestTimeEpoch": 1598726145145,
        "resourceId": "7uw8tx",
        "resourcePath": "/webhook",
        "stage": "test-invoke-stage"
    },
    "resource": "/webhook",
    "stageVariables": null
}
```

It looks like `resource` field is missing in `ApiGateway` enum value. Also I see that `requestContext` contains additional fields...

I could try fixing it myself, but I'm not sure about right approach: Should I just add missing fields and ignore them?

**Comment by softprops** [comment]
Can you share a few extra pieces of information

1) how are you triggering the lambda? I.e. with a sample json payload, curl request, aws console test GUI

2) have you modified the trigger configuration and if so can you share the diff here?

**Comment by tocisz** [comment]
I do this with AWS (web) console. I have LAMBDA_PROXY integration defined:
![screen1](https://tomasz-cichocki.pl/img/api_gw.png)

I click on "Test" (above on the left), select "GET" method (leaving everything else empty), and click blue "Test" button.
![screen2](https://tomasz-cichocki.pl/img/api_gw2.png)

I think I haven't modified trigger configuration - not sure what you mean...

**Comment by softprops** [comment]
In order to register a lambda with a service integration,  you specify the type of service integration and integration configuration a config file, typically serverless.yml or aws sam template.

I'm the case of the example template linked above it's set up to be [triggered on GET requests to /]( https://github.com/softprops/serverless-aws-rust-http/blob/bb7268bb3312bd8cdbbe0958a91278fc0113e83f/serverless.yml#L55).

In your example, you've registered a /webhook path to the integration so it ends out being a slightly different configuration than the example template. If you've done that in the serverless.yml file, could you share the diff?

Could you try the same test with curl? This will invoke your lambda with a more realistic payload.

I find that the aws console GUI sample payloads are sometimes not always accurate representations of the actual integration payloads.

**Comment by tocisz** [comment]
Indeed, when doing request by `curl` everything works fine. I compared *curl*-request and *test*-request. The problem was `headers` being `null`. When I entered `Host:anything.com` into headers text area, generated *test*-request is also handled correctly.
