### ISSUE TITLE
Linker related error when building on Windows 10

### ISSUE THREAD

**Issue by myyrakle** [awslabs/aws-lambda-rust-runtime#273]
![image](https://user-images.githubusercontent.com/16988115/101979998-564ba300-3ca5-11eb-83c6-958a33993ce4.png)
When I try to build with the provided source in windows 10 environment, I get the above error.
When I went into WSL Ubuntu and tested it with the same source, there were no problems.

The compiler version is almost the latest 1.48.
![image](https://user-images.githubusercontent.com/16988115/101980010-6cf1fa00-3ca5-11eb-82f1-3ad79614f6b5.png)

Windows version
Windows 10 Pro 19041.630.

**Comment by calavera** [comment]
The `cc` linker is not available on windows, and you'll never be able to build for `linux-musl` on windows natively without it. You can use something like https://github.com/rust-embedded/cross but that uses Docker to actually compile to different targets that are not supported in the host OS.

I'm on Windows 10 too, and I always use WSL for this specific gotcha too.

**Comment by bahildebrand** [comment]
Closing this as @calavera response fully covers the issues. Feel free to reopen if you still have questions.

**Comment by AndreKR** [comment]
The answer is mostly wrong. As long as your code and it's dependencies are pure Rust, you can build for target `x86_64-unknown-linux-musl` on Windows simply by putting
```toml
[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
```
into your [cargo config](https://doc.rust-lang.org/cargo/reference/config.html) (not `Cargo.toml`!). It will then use the bundled LLD (LLVM's linker) to link.

It gets more complicated if any dependencies use C code though, because you'll also need a toolchain that can cross-compile the C dependency.
