### ISSUE TITLE
Problem with Error type not Sized 

### ISSUE THREAD

**Issue by chroche** [awslabs/aws-lambda-rust-runtime#316]
Hi,

I'm getting he following compilation error trying to use `lambda_runtime` v0.3 with the following setup:
```rust
use serde_json::Value;
use lambda_runtime::{handler_fn, run, Context, Error};

#[tokio::main(flavor="current_thread")]
async fn main() -> Result<(), Error> {

  let func = handler_fn(func);
  run(func).await?;
  Ok(())
}

async fn func(_: Value, _: Context) -> Result<(), Error> {

  event::event_loop().await?;
  Ok(())
}

mod event {
  use std::error::Error;
  pub async fn event_loop() -> Result<(), Box<dyn Error>> {
[...]
  }
}
```
This gives me:
```bash
> cargo build --bin bootstrap --features lambda
error[E0277]: the size for values of type `dyn std::error::Error` cannot be known at compilation time
  --> src/lambda.rs:26:28
   |
26 |   event::event_loop().await?;
   |                            ^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `dyn std::error::Error`
   = note: required because of the requirements on the impl of `std::error::Error` for `Box<dyn std::error::Error>`
   = note: required because of the requirements on the impl of `From<Box<dyn std::error::Error>>` for `Box<dyn std::error::Error + Sync + std::marker::Send>`
   = note: required by `from`
```

I can't seem to move around it, can somebody help?

The code compiles fine with a standard `main` function:
```rust
use std::error::Error;

#[tokio::main(flavor="current_thread")]
async fn main() -> Result<(), Box<dyn Error>> {

  event::event_loop().await?;
  Ok(())
}
```

Thanks,
Chris

**Comment by chroche** [comment]
Hi,

thanks for the prompt answer. The compiler seems unhappy with the fix though:
```
error[E0225]: only auto traits can be used as additional traits in a trait object
  --> src/event.rs:13:57
   |
13 | pub async fn event_loop() -> Result<(), Box<dyn Error + Sized>> {
   |                                                 -----   ^^^^^ additional non-auto trait
   |                                                 |
   |                                                 first non-auto trait
```
The errors in the `event_loop` come mostly from Rusoto v.0.46 if that helps.

**Comment by davidbarsky** [comment]
@chroche: I'm pretty sure that the error mentioning `Sized` is a red herring, or at the very least, extremely misleading. The two trait objects (`Box<dyn Error + Send + Sync + 'static>`, aliased to `lambda_runtime::Error` and `Box<dyn Error>`) are _both_ sized thanks to the `Box`. However, the additional trait bounds on `lambda_runtime::Error` mean that `dyn Error` is a different trait object with a different underlying vtable (I believe!), which gives you the misleading error that complains about `Sized`—see [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=256444b1d3d446d0f68af0b14fd4fffe) for a minimal reproduction.

There are two ways to resolve this issue:

- Change `event_loop` to return a `Box<dyn Error + Send + Sync + 'static>`.
- Change `event_loop` to return a concrete error that can be cast to `Box<dyn Error + Send + Sync + 'static>`—most errors in Rust will _just work_ due to the automatic `From` call that `?` makes.

**Comment by TransientError** [comment]
Sorry, I was on mobile, so I didn't get a chance to test it yet. I can get to it later today probably. In the meantime, I'd try using the lambda_runtime Error directly instead of the `Box<dyn Error>` and seeing if that works.

**Comment by chroche** [comment]
Hi,

yes in fact the crux of the problem seems to be related to the `Send` trait really, as I'm now getting this after updating the `Error` type:
```rust
#[tokio::main(flavor="current_thread")]
async fn main() -> Result <(), Box<dyn Error + Send + Sync + 'static>> {

  let lambda_handler = handler_fn(lambda_handler);
  run(lambda_handler).await?;
  Ok(())
}

async fn lambda_handler(_: Value, _: Context) -> Result <(), Box<dyn Error + Send + Sync + 'static>> {

  event::event_loop().await?;
  Ok(())
}
```
gives
```
error: future cannot be sent between threads safely
  --> src/lambda.rs:20:3
   |
20 |   run(lambda_handler).await?;
   |   ^^^ future returned by `lambda_handler` is not `Send`
   |
   = help: within `impl futures::Future`, the trait `std::marker::Send` is not implemented for `Rc<Vec<AsgStatus>>`
note: future is not `Send` as this value is used across an await
  --> src/event.rs:59:42
```
That sounds even more scary :-/

**Comment by bahildebrand** [comment]
You need to declare `Rc<Vec<AsgStatus>>` as `Arc<Vec<AsgStatus>>` instead. If you look at the doc pages for [Rc](https://doc.rust-lang.org/std/rc/struct.Rc.html) and [Arc](https://doc.rust-lang.org/std/sync/struct.Arc.html) you'll see that Arc implements Send while Rc does not. This is required as the Tokio runtime can move tasks to new threads across await points.

**Comment by chroche** [comment]
Ok but I thought I had managed to avoid having to do that up to now using a single-threaded Tokio runtime. Is it not possible to keep things this way when using `lambda_runtime`?

**Comment by davidbarsky** [comment]
Not at the moment. Internally, we use a `tokio::task::spawn` to catch panics and report them to the Lambda API. The bounds of `spawn` don't differ between the local thread and work-stealing variants of Tokio's runtimes.

I think this issue is surmountable, but the final decision should be with the maintainers of this project who'd have a better idea as to what the Lambda team is planning.

**Comment by chroche** [comment]
Hi guys,

with the suggested fixes the code now compiles and runs fine both in local Docker and AWS Lambda.

Thanks everybody for the valuable help!
Chris
