### ISSUE TITLE
non-async version?

### ISSUE THREAD

**Issue by DartMen** [awslabs/aws-lambda-rust-runtime#317]
Would it be possible to have a lightweight 'blocking' version without Tokio/Hyper dependencies?

Consider the following repo names:
aws-lambda-rust-runtime
aws-lambda-rust-runtime-async

Here is some recent discussion about the need for async by John-Nagle:

> Async is really needed only for a specific class of programs - those that are both I/O bound and need to maintain a large number of network connections. Outside of that niche, you don't really need it. We already have threads, after all. Not everyone is writing a web service.

https://github.com/rust-lang/wg-async-foundations/issues/58

**Comment by softprops** [comment]
A few items of note.

Async workloads. I think, and I haven't tried this it should be sufficiently easy to wrap sync workloads in `async |move| { }` or something of the like. You are correct in that not all workloads have async implementations and to some degree lambda, the hosting platform, _is_ a provides your application with concurrency levers, but a large number of networked services interactions typically guide you in an async direction. For that reason I think it still makes sense as the default.

Async runtimes. The way this and other lambda runtimes work is through an internal api expects to be polled for events based on registered triggers, dispatches control to your function with those event payloads, and responds back with a response to that internal api for those triggers. In order to get the most performance and value out of your lambda task, a small semi ephemeral process that runs your function code, it's behoving to allow function invocations to make independent progress and not serialize their invocations. In a tasks lifetime, more than one invocation can be making progress at a time regardless of what form its workload takes on. 

Since the runtime is compiled in as a runtime dependency and that needs to talk to the internal lambda api I don't think you can get away with a hyper free runtime. Since the runtime is able to be come more runtime efficient through using hyper in an async fashion I don't think you can get away with tokio dependencies. 

However for sync workloads there might be some area for a helper interface though I don't know that it would provide much more than a wrapper around an `async |move| { }` closure

**Comment by bahildebrand** [comment]
Can I ask if there is an underlying issue you're running into that sparked this request? You mention lightweight, are you finding your binary sizes too large? The reason I ask is that while it would be possible to support this request, it would be a significant amount of work, and we would need a pretty good use case to justify it.

As @softprops mentioned the current implementation is tied pretty heavily into the Tokio runtime, so we'd need to bring in another dependency other than Hyper/Tokio, and design an alternative path to service the Lambda Runtime API. I do, however, like the idea of a sync wrapper that @softprops mentioned. If that is feasible it could be a good middle ground here.

**Comment by DartMen** [comment]
Ive been using async/futures extensively over the last years in many different languages and it's without a doubt a fantastic mechanism.

But I would rather have a choice to use it or not, like for example, just fetching the weather forecast synchronously once a day.

To run the following example, it needs to pull in many packages which increases not only build times, but also attack surface.
```rust
fn main() {
    println!("Hello, world!");
}
```

With lightweight, I meant, the bare-minimum packages needed to just be able to execute `println!("Hello, world!");`

The proposal for `async |move| { }` would defeat my request, as in this case, I would rather just keep using async/await anyway because I am kind of forced to do so?

It's not about just running synchronous code, but to run it with bare-minimum package requirements.

The Rust folks just released a blog post about the future of async which might add to the discussion, and considerations:
https://blog.rust-lang.org/2021/04/14/async-vision-doc-shiny-future.html

**Comment by bahildebrand** [comment]
Unfortunately the bare minimum to execute a simple print statement will always be rather large for this library. Even if we were to take out our tokio/hyper dependency we would need to bring in another http client to service the [runtime api](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html). I haven't done any direct comparisons of other http libraries, but I would imagine they would be comparable in the number of depencies. Additionally some of the more popular libraries wrap the c version of curl which would bring it's own attack surface considerations.

**Comment by coltonweaver** [comment]
Yeah after looking into this a good bit, it would require a decent amount of effort to get going. I'm definitely open to the idea of this, but I can't see this being a priority for some time.

**Comment by duaneking** [comment]
I'm running into this same issue.

The core issue is pretty simple to describe; every millisecond we waste with code that isn't needed costs us more with Lambda  A thread is an expensive operation, and since we are do not need that tread, its seen as expensive and wasteful from an engineering excellence perspective.  Every millisecond counts. For many charities that need the sort of systems that need rust on Lambda, every millisecond is the difference between them having the funds for their  mission or being forced to close their doors and put out the candle they are trying to light against the darkness they are fighting.

Speed should be your critical priority here, and forcing async code on people where that is a total waste when its not needed - your  forcing the current process to stop so it can yield  and create that thread so its a huge delay you just do not need - makes it look like your goals are not aligned to these customer efforts to optimize for speed and reliability.

This library has a lot of dependencies that it does not need.  Please allow us to not be forced into async hell or slow down our systems due to this bad architecture.

**Comment by davidbarsky** [comment]
While I don't maintain this library anymore (as I no longer work at Amazon and will be starting a new job soon), I figured that I should explain my thinking about making the runtime async-first. I'll first try to respond to @duaneking's points.

> A thread is an expensive operation, and since we are do not need that thread, its seen as expensive and wasteful from an engineering excellence perspective.

I think that there's might be misunderstanding here: it is _entirely_ possible (and encouraged, if you know what performance profile you need) to run your Lambda function on a [single-threaded Tokio executor](https://docs.rs/tokio/1.11.0/tokio/runtime/struct.Builder.html#method.new_current_thread).

> Speed should be your critical priority here, and forcing async code on people where that is a total waste when its not needed - you are forcing the current process to stop so it can yield and create that thread so its a huge delay you just do not need - makes it look like your goals are not aligned to these customer efforts to optimize for speed and reliability.

There are no threads being spawned in the background without your knowledge or action.

> This library has a lot of dependencies that it does not need. Please allow us to not be forced into async hell or slow down our systems due to this architecture.

While I think that there's an opportunity to have this library adopt a sans-IO approach, I personally struggle to think of what dependencies can be safely removed without a non-trivial amount of engineering work. Can you let me know what dependencies you feel are unnecessary?

> What should be happening is this should be split into 2 libs, one sync and one async, and the async lib simply uses the sync lib so people can use whatever. Simple, DRY, SOLID. Not this moist code.

While I think it'd be helpful to have both a synchronous and an asynchronous version of this library, I'll note that I believe that the synchronous library _needs_ to be built atop of the asynchronous one (as opposed to your proposal, which has the layering flipped) in order to achieve the performance (namely, _latency_ goals) that customers using an asynchronous version require.

---

I couldn't state this at the time when I was working on this library, but I knew that the AWS Rust SDK would be asynchronous-first, with synchronous clients added later. It didn't really make _sense_ to ship this library as being synchronous-first only to require customers to pull in a futures executor anyways.

**Comment by duaneking** [comment]
I don't really appreciate being mentioned directly as I was trying to focus on the code and not make it about personal attacks against customers like myself who experience consistent issues and get no support despite paying for it.  And the way you wrote that, it does not makes me think you are trying to respond fully constructively.

But ok, I'm feeling forced to engage.  Lets hope you gain some empathy.

> I think that there's might be misunderstanding here: it is entirely possible (and encouraged, if you know what performance profile you need) to run your Lambda function on a single-threaded Tokio executor.

Yes I do think there has been a misunderstanding. The AWS docs I was listening to speak as if the architecture you describe as being optimal does not actually exist. If you have secret data as a prior employee you want to make public, great, happy to let you do so.  But I think its reasonable to also state that such data should not be assumed as available to anybody, either.

> There are no threads being spawned in the background without your knowledge or action.

That's my point.  This is multiple issues, being conflated. But its clear I'm not going to get good faith efforts to separate them and resolve them here based on the response I just got, so please lets just skip it.

This is part of a greater issue on docs and transparency with these parts of the system to allow integration;  My experiences with AWS this past year has completely dissolved my trust as a customer, as AWS seems to actively run away from serving customers in my experiences trying to get even extremely basic - paid! - support and just not getting it.

That seems like a lot of overhead over just translating the event schemas passed into it and then routing it to a handler directly without needing to spin up extra infrastructure that could be skipped, trimming a few ms off the request->response cycle.

> While I think it'd be helpful to have both a synchronous and an asynchronous version of this library, I'll note that I believe that the synchronous library needs to be built atop of the asynchronous one (as opposed to your proposal, which has the layering flipped) in order to achieve the performance (namely, latency goals) that customers using an asynchronous version require.

The Sync versions goal should be to have no async code called in it. Anything else would not make sense.

Another problem with code runtimes being async by default on lambda is that scheduling overhead would be now baked in as a cost that we as customers can not control but are still being billed for in a super non-transparent way, due to what I believe to be among other things, a conflict of interest that exists when that task takes longer to execute because AWS may have chosen to run it in the most profitable way that itself may not have been the fastest way.  Sure, we like the idea of the current request being executed immediately with no delay.. but we also all know that that's not the case in a lot of systems.  Enqueuing is a O(1) operation, and considered to be fast, but its still not 0.  Same with checking the queue, initializing a scheduler, etc. 

It doesn't benefit me as a customer to have my workload being billed by the millisecond to include extra scheduling or API bloat, and such that would inherently delay the execution of the task and thus delay the generation and emit of the response.

I found this library trying to find a solution and I'm still looking for a solution; A solution is/was all I care/cared about posting here. I would much rather not get sucked into a non-constructive debate.  Thanks.

**Comment by calavera** [comment]
hey folks, we've decided not to do this for the time being, if anything changes, I'll let you know.
