### ISSUE TITLE
Cannot use RUST for ARM Graviton2 Lambda

### ISSUE THREAD

**Issue by Aleksandr-Filichkin** [awslabs/aws-lambda-rust-runtime#354]
Hi Everyone,

I'm trying to deploy RUST lambda for ARM lambda. I was able to compile the code for target 'aarch64-unknown-linux-gnu', but during invocation, I see such an error:
`/var/task/bootstrap: line 3:     9 Segmentation fault      (core dumped) ./app
END RequestId: 048e5e8c-538a-4447-b917-b46414c3d377
REPORT RequestId: 048e5e8c-538a-4447-b917-b46414c3d377	Duration: 212.24 ms	Billed Duration: 257 ms	Memory Size: 256 MB	Max Memory Used: 37 MB	Init Duration: 44.59 ms	XRAY TraceId: 1-616e7dfc-07e7e2237a96edf63c5b43e7	SegmentId: 2d628b5e454f8dee	Sampled: true
RequestId: 048e5e8c-538a-4447-b917-b46414c3d377 Error: Runtime exited with error: exit status 139Runtime.ExitError`

All code you can find here (https://github.com/Aleksandr-Filichkin/aws-lambda-runtimes-performance/blob/arm-lambda/rust-aws-lambda/Dockerfile.arm)

The code works for the non-arm Lambda

**Comment by brainstorm** [comment]
Hello @Aleksandr-Filichkin my example code runs fine on ARM64 sans MUSL and it does not segfault, take a peek, happy to guide you through if there's something unclear?:

https://github.com/umccr/s3-rust-noodles-bam

I just use a very thin mod of the `provided.al2` official image: https://github.com/umccr/s3-rust-noodles-bam/blob/master/Dockerfile-provided.al2

**Comment by simonvandel** [comment]
@Aleksandr-Filichkin

The docker image you are using to build the rust code uses glibc 2.28 as seen here https://github.com/docker-library/repo-info/blob/a1ebff8be128ff3af7692c79f98ffb7ece0cec63/repos/rust/local/1.54.md#dpkg-source-package-glibc228-10

But Afaikt Amazon Linux 2 only has 2.26 https://aws.amazon.com/amazon-linux-2/release-notes/

You can try building the rust code in a docker image based directly on Amazon Linux 2, so that you are certain that the Glibc version is compatible. You can get the latest rust compiler using rustup.

**Comment by coltonweaver** [comment]
Hey! Have you given the latest README steps a shot? I was able to compile and run examples on ARM using Docker (on Apple silicon).

**Comment by nmoutschen** [comment]
Hey @Aleksandr-Filichkin !

I see that you've [made changes in your repository](https://github.com/Aleksandr-Filichkin/aws-lambda-runtimes-performance/commit/550b7496b151442cfbb4e380e5463829f8f501e2), so I will close this issue assuming that you made it work. Feel free to  reopen with a status update if it's not the case.
