### ISSUE TITLE
How can I use an external library that is not thread safe?

### ISSUE THREAD

**Issue by mehmetcansahin** [awslabs/aws-lambda-rust-runtime#478]
Hello, when I use an external library, I get the error "generator cannot be sent between threads safely". I couldn't find what to do as there is an external library for this.

```
generator cannot be sent between threads safely
within `tendril::tendril::NonAtomic`, the trait `Sync` is not implemented for `Cell<usize>`rustc
lib.rs(166, 16): required by a bound in `lambda_http::run`
generator cannot be sent between threads safely
within `ego_tree::Node<scraper::node::Node>`, the trait `Sync` is not implemented for `Cell<NonZeroUsize>`rustc
lib.rs(166, 16): required by a bound in `lambda_http::run`
generator cannot be sent between threads safely
within `ego_tree::Node<scraper::node::Node>`, the trait `Sync` is not implemented for `UnsafeCell<tendril::tendril::Buffer>`rustc
lib.rs(166, 16): required by a bound in `lambda_http::run`
generator cannot be sent between threads safely
within `ego_tree::Node<scraper::node::Node>`, the trait `Sync` is not implemented for `*mut tendril::fmt::UTF8`rustc
lib.rs(166, 16): required by a bound in `lambda_http::run`
```

**Comment by calavera** [comment]
Hi @mehmetcansahin ,

As the compiler says in `the trait `Sync` is not implemented for `Cell<usize>`rustc`, you're using objects that don't implement traits that make them thread safe. This problem is originated in the libraries that you're using, not in the Lambda runtime. I would open an issue in the `tendril` repository to discuss thread safety with its maintainers, I don't know anything about that project.

You can read more about general thread safety in Rust in this article: https://onesignal.com/blog/thread-safety-rust/
