### ISSUE TITLE
Missing libraries when building

### ISSUE THREAD

**Issue by UMR1352** [awslabs/aws-lambda-rust-runtime#496]
After I added the mysql crate to my project, building with `cargo lambda build --release` gives me the following error:
```
= note: warning: unsupported linker arg: -znoexecstack
          warning: unsupported linker arg: -zrelro
          warning: unsupported linker arg: -znow
          ld.lld: error: unable to find library -lssl
          ld.lld: error: unable to find library -lcrypto
          ld.lld: error: unable to find library -lz
```
My system is up to date (I'm on arch) and so is my rust toolchain
How can I fix this? Where should I add the missing libraries or how can I check if I have them installed somewhere? Sorry for the noob question. Thanks in advance.

**Comment by sdd** [comment]
I've been getting the same issue for a few months. It is an issue with cargo-lambda on certain Linux distros, rather than aws-lambda-rust-runtime. It works for some of my projects that use aws-lambda-rust-runtime - just not any that use the `reqwest` library.

If I use cargo-lamba on a project that depends on `reqwest`,  it causes the `-lssl` and `-lcrypto` args to be passed to zigcc. zigcc then fails, spitting out those `ld.lld: error: unable to find library -lssl` and `ld.lld: error: unable to find library -lcrypto` errors.

I'm on Manjaro Linux, an Arch Linux derivative. I suspect that there is something about the environment or file paths on Manjaro that is causing zigcc problems.

**Comment by sdd** [comment]
This happens with `rustls-tls` and `native-tls`. Oh wow, on the offchance I just tried `native-tls-vendored` and it successfully compiled! Awesome, I'll deploy and see if it works.

I'm not sure if this will solve all of @UMR1352 's build issues though as I'm not using anything that causes my project to require `-lz`.

**Comment by sdd** [comment]
I thought that too, but I can see the libraries present in both /lib and /usr/lib as symlinks.

The good news is that the resulting lambda.zip worked fine with native-tls-vendored.

I'm sure this issue will crop up again, maybe if I do something using zlib like the OP.

**Comment by UMR1352** [comment]
> @UMR1352 thanks for opening this issue. At first glance, it looks like the linker is having issues finding system libraries.
> 
> Since you're running on Linux, can you try running `cargo build --release` and see if the output is the same? Do you know which native libraries you're using in your function? do you have a dependency on OpenSSL?

Thanks for your help, unfortunately building directly using `cargo build --release` works just fine without any issues. I have no direct dependency to either reqwest or openssl. `mysql` crate seems to be the origin of the problem, since before adding it the project was building just fine.

**Comment by UMR1352** [comment]
I checked, `mysql` depends on `native-tls` and on `flate2` which depends on `zlib`. So `-lssl, -lcrypto, -lz` come from `mysql`. 
I managed to solve the building error by changing features: `rustls-tls` as TLS backend for `mysql` and `miniz-oxide` for `flate2`
